server:
    port: 8080
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/pge
        username: postgres
        password: s@bir326
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true
            javax:
                persistence:
                    validation:
                        mode: none
    security:
        user:
            name: test
            password: test
logging:
    level:
        root: WARN
        com:
            baeldung: TRACE
